#!/usr/bin/env node
/**
 * Per-repo navigation map generator.
 *
 * Scans this repo's source tree and (re)writes the AUTO section of MAP.md
 * (between the <!-- AUTO:START --> / <!-- AUTO:END --> markers). Everything
 * outside the markers — the "Where to look" table, notes — is preserved.
 *
 * Zero dependencies. Run from the repo root:  node scripts/gen-map.mjs
 *
 * Design goal: agents read a small per-repo map instead of one big file, and
 * the volatile lists (features/domains/routes) never go stale because they are
 * derived from the actual folders.
 */
import { readdirSync, existsSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, basename } from "node:path";

const ROOT = process.cwd();
const repo = basename(ROOT);

const START = "<!-- AUTO:START -->";
const END = "<!-- AUTO:END -->";

/** List immediate subdirectories of a path (sorted, dirs only). */
function dirs(p) {
  const abs = join(ROOT, p);
  if (!existsSync(abs)) return [];
  return readdirSync(abs)
    .filter((n) => !n.startsWith(".") && statSync(join(abs, n)).isDirectory())
    .sort();
}

/** List source files (tsx/ts) in a path, sorted, basenames only. */
function files(p, ext = [".tsx", ".ts"]) {
  const abs = join(ROOT, p);
  if (!existsSync(abs)) return [];
  return readdirSync(abs)
    .filter((n) => ext.some((e) => n.endsWith(e)) && !n.endsWith(".d.ts"))
    .map((n) => n.replace(/\.(tsx|ts)$/, ""))
    .sort();
}

const list = (arr) => (arr.length ? "`" + arr.join("`, `") + "`" : "_(none)_");

/**
 * Each known repo describes which folders to scan and how to label them.
 * Unknown repos fall back to a generic features/app scan.
 */
function buildAuto() {
  const lines = [];
  const add = (label, items) => {
    if (items.length) lines.push(`- **${label}** (${items.length}): ${list(items)}`);
  };

  // Backend (Clean Architecture, optionally with RouteContract pilot)
  if (existsSync(join(ROOT, "src/Application/services"))) {
    add("Domains (services)", dirs("src/Application/services"));
    add("Routes (legacy pattern)", dirs("src/Presentation/routes"));
    if (existsSync(join(ROOT, "src/Presentation/contracts"))) {
      add("Domains on RouteContract pattern", dirs("src/Presentation/contracts"));
    }
    add("Repositories", dirs("src/Infrastructure/repositories"));
    return lines;
  }
  // SDK generator (openapi-generator scripts/config, no src/)
  if (existsSync(join(ROOT, "scripts")) && existsSync(join(ROOT, "config")) && !existsSync(join(ROOT, "src"))) {
    add("Generator scripts", files("scripts", [".ts"]));
    add("Generator configs", files("config", [".json"]));
    return lines;
  }
  // SDK
  if (existsSync(join(ROOT, "src/resources"))) {
    add("SDK resources", dirs("src/resources"));
    add("Top-level", dirs("src"));
    return lines;
  }
  // Microservices monorepo (pdf/excel/mail/storage)
  if (["pdf", "excel", "mail", "storage"].some((s) => existsSync(join(ROOT, s, "src")))) {
    for (const svc of ["pdf", "excel", "mail", "storage"]) {
      if (existsSync(join(ROOT, svc, "src"))) {
        const routes = files(`${svc}/src/routes`).map((r) => r.replace(/Route$/, ""));
        add(`${svc}/ routes`, routes);
      }
    }
    return lines;
  }
  // Service-platform dashboard
  if (existsSync(join(ROOT, "dashboard/src/pages"))) {
    add("Pages", files("dashboard/src/pages"));
    return lines;
  }
  // Frontend (features + optional Next app router)
  if (existsSync(join(ROOT, "src/features"))) {
    add("Features", dirs("src/features"));
    if (existsSync(join(ROOT, "src/app"))) add("App routes", dirs("src/app"));
    return lines;
  }
  // Design system / fallback
  if (existsSync(join(ROOT, "src/components"))) {
    add("Components", dirs("src/components"));
  }
  if (!lines.length) lines.push("_No recognized source layout. Update scripts/gen-map.mjs._");
  return lines;
}

const auto = [
  `_Generated by \`scripts/gen-map.mjs\` — do not edit between the markers; run the script._`,
  "",
  ...buildAuto(),
].join("\n");

const mapPath = join(ROOT, "MAP.md");
let content;

if (existsSync(mapPath)) {
  const cur = readFileSync(mapPath, "utf8");
  if (cur.includes(START) && cur.includes(END)) {
    content = cur.replace(
      new RegExp(`${START}[\\s\\S]*?${END}`),
      `${START}\n${auto}\n${END}`,
    );
  } else {
    content = cur.trimEnd() + `\n\n## Structure\n\n${START}\n${auto}\n${END}\n`;
  }
} else {
  // First-time scaffold: AUTO section + an editable "Where to look" stub.
  content = `# ${repo} — Map

> Per-repo navigation map. Read this before exploring. See repo \`CLAUDE.md\`/\`AGENTS.md\` for rules.

## Structure

${START}
${auto}
${END}

## Where to look (manual — keep terse)

| Task | Start here |
|---|---|
| _add task_ | _path_ |
`;
}

writeFileSync(mapPath, content);
console.log(`[gen-map] ${repo}: MAP.md ${existsSync(mapPath) ? "updated" : "created"}`);
